
    create table activity_types (
        id bigint generated by default as identity,
        code varchar(255) not null unique,
        display_name varchar(255),
        primary key (id)
    );

    create table events (
        end_time timestamp(6),
        id bigint generated by default as identity,
        start_time timestamp(6) not null,
        city varchar(255),
        country varchar(255),
        description varchar(255),
        name varchar(255) not null,
        primary key (id)
    );

    create table health_metrics (
        heart_rate integer,
        height float(53),
        weight float(53),
        date timestamp(6),
        id bigint generated by default as identity,
        user_id bigint not null,
        primary key (id)
    );

    create table statistics (
        total_calories_burned integer not null,
        total_distance float(53) not null,
        total_trainings integer not null,
        id bigint generated by default as identity,
        user_id bigint not null unique,
        primary key (id)
    );

    create table trainings (
        average_speed float(53) not null,
        distance float(53) not null,
        activity_type_id bigint not null,
        end_time timestamp(6),
        id bigint generated by default as identity,
        start_time timestamp(6) not null,
        user_id bigint not null,
        primary key (id)
    );

    create table user_events (
        event_id bigint not null,
        id bigint generated by default as identity,
        user_id bigint not null,
        status varchar(255),
        primary key (id)
    );

    create table users (
        birthdate timestamp(6) not null,
        id bigint generated by default as identity,
        email varchar(255) not null unique,
        first_name varchar(255),
        last_name varchar(255),
        primary key (id)
    );

    create table workout_sessions (
        altitude float(53) not null,
        end_latitude float(53) not null,
        end_longitude float(53) not null,
        start_latitude float(53) not null,
        start_longitude float(53) not null,
        id bigint generated by default as identity,
        training_id bigint not null unique,
        timestamp varchar(255) not null,
        primary key (id)
    );

    alter table if exists health_metrics 
       add constraint FK887uooe4p0l3kwmyplbdd9tjd 
       foreign key (user_id) 
       references users;

    alter table if exists statistics 
       add constraint FKgubpcsln9g1fvbi3f5sgt5def 
       foreign key (user_id) 
       references users;

    alter table if exists trainings 
       add constraint FKkt44oiiupxxogv1fwuj0b6g2 
       foreign key (activity_type_id) 
       references activity_types;

    alter table if exists trainings 
       add constraint FK32ir33u28fo97252hksjvlubp 
       foreign key (user_id) 
       references users;

    alter table if exists user_events 
       add constraint FKqh8jukuil4jkihri1o262hik7 
       foreign key (event_id) 
       references events;

    alter table if exists user_events 
       add constraint FKg3rv1yxrs56ohyn30rlt7vum7 
       foreign key (user_id) 
       references users;

    alter table if exists workout_sessions 
       add constraint FKs4ahs2fmypwll5fb5k9wmimc5 
       foreign key (training_id) 
       references trainings;
